services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: tennis-tracking-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: tennis_admin_2024
      MONGO_INITDB_DATABASE: tennis_tracking
    volumes:
      - mongodb_data:/data/db
      - ./backend/scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - tennis-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  # Redis for caching and session management
  redis:
    image: redis:7-alpine
    container_name: tennis-tracking-redis
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - tennis-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tennis-tracking-backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://admin:tennis_admin_2024@mongodb:27017/tennis_tracking?authSource=admin
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - JWT_ALGORITHM=HS256
      - JWT_EXPIRATION_HOURS=24
      - UPLOAD_DIR=/app/uploads
      - CORS_ORIGINS=http://localhost:3000,http://frontend:3000
      - ENVIRONMENT=development
    volumes:
      - ./backend:/app
      - uploads_data:/app/uploads
      - ./models:/app/models
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - tennis-network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://localhost:8000
    container_name: tennis-tracking-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
      - VITE_WS_URL=ws://localhost:8000
    depends_on:
      - backend
    networks:
      - tennis-network

  # Video Processing Worker (for async processing)
  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile.worker
    container_name: tennis-tracking-worker
    restart: always
    environment:
      - MONGODB_URL=mongodb://admin:tennis_admin_2024@mongodb:27017/tennis_tracking?authSource=admin
      - REDIS_URL=redis://redis:6379
      - MODEL_PATH=/app/models
    volumes:
      - ./backend:/app
      - uploads_data:/app/uploads
      - ./models:/app/models
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - tennis-network
    command: celery -A app.worker worker --loglevel=info

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local
  uploads_data:
    driver: local

networks:
  tennis-network:
    driver: bridge